### ISSUE TITLE
Some Q&A posts have excess whitespace at the bottom

### ISSUE THREAD

**Issue by tdnzr** [ForumMagnum/ForumMagnum#7888]
See [this screenshot](https://i.imgur.com/9XBrppn.png) of [this post](https://www.lesswrong.com/posts/PKw5h7aeHNywirJoi/would-you-pay-for-a-search-engine-limited-to-rationalist).

**Comment by jpaddison3** [comment]
The offending css:

```css
.PostsPage-commentsSection {
    min-height: calc(70vh - 100px);
    [...]
}
```

Seems to interact badly with questions in particular, though it does seem excessive in general.
